// <auto-generated />
using System;
using Eindwerk__Gegevensbeheer__en_C_sharp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Eindwerk__Gegevensbeheer__en_C_sharp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230523013859_added leveranciers table")]
    partial class addedleverancierstable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("Eindwerk__Gegevensbeheer__en_C_sharp.Models.Auto", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Bouwjaar")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Merk")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Prijs")
                        .HasColumnType("REAL");

                    b.Property<int>("Voorraad")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Autos");
                });

            modelBuilder.Entity("Eindwerk__Gegevensbeheer__en_C_sharp.Models.BestellingM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Aantal")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AutoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("KlantId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OnderdeelId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("TotaalPrijs")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("AutoId");

                    b.HasIndex("KlantId");

                    b.HasIndex("OnderdeelId");

                    b.ToTable("Bestellingen");
                });

            modelBuilder.Entity("Eindwerk__Gegevensbeheer__en_C_sharp.Models.Klant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Achternaam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Email")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("IVEmail")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("IVTelefoonNummer")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("TelefoonNummer")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Voornaam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Klanten");
                });

            modelBuilder.Entity("Eindwerk__Gegevensbeheer__en_C_sharp.Models.Leverancier", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TelefoonNummer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Leveranciers");
                });

            modelBuilder.Entity("Eindwerk__Gegevensbeheer__en_C_sharp.Models.Onderdeel", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Prijs")
                        .HasColumnType("REAL");

                    b.Property<int>("Voorraad")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Onderdelen");
                });

            modelBuilder.Entity("Eindwerk__Gegevensbeheer__en_C_sharp.Models.User", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Gebruikersnaam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Wachtwoord")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Eindwerk__Gegevensbeheer__en_C_sharp.Models.BestellingM", b =>
                {
                    b.HasOne("Eindwerk__Gegevensbeheer__en_C_sharp.Models.Auto", "Auto")
                        .WithMany()
                        .HasForeignKey("AutoId");

                    b.HasOne("Eindwerk__Gegevensbeheer__en_C_sharp.Models.Klant", "Klant")
                        .WithMany()
                        .HasForeignKey("KlantId");

                    b.HasOne("Eindwerk__Gegevensbeheer__en_C_sharp.Models.Onderdeel", "Onderdeel")
                        .WithMany()
                        .HasForeignKey("OnderdeelId");

                    b.Navigation("Auto");

                    b.Navigation("Klant");

                    b.Navigation("Onderdeel");
                });
#pragma warning restore 612, 618
        }
    }
}
